name: Terraform

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Ambiente"
        required: true
        type: choice
        options:
          - dev
          - staging
          - producao
          - zabbix
      action:
        description: "Ação do Terraform"
        required: true
        default: "plan"
        type: choice
        options:
          - plan
          - apply
          - destroy
      confirm_destroy:
        description: "Digite DESTROY para confirmar"
        required: false

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment == 'producao' && 'producao' || github.event.inputs.environment == 'staging' && 'staging' || 'dev' }}

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configurar AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Terraform Init
        working-directory: environments/${{ github.event.inputs.environment }}
        run: terraform init

      - name: Terraform Plan
        if: ${{ github.event.inputs.action == 'plan' }}
        working-directory: environments/${{ github.event.inputs.environment }}
        run: terraform plan -var-file="terraform.tfvars"

      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'apply' }}
        working-directory: environments/${{ github.event.inputs.environment }}
        run: terraform apply -var-file="terraform.tfvars" -auto-approve

      - name: Terraform Destroy
        if: >
          github.event.inputs.action == 'destroy' &&
          github.event.inputs.confirm_destroy == 'DESTROY'
        working-directory: environments/${{ github.event.inputs.environment }}
        run: terraform destroy -var-file="terraform.tfvars" -auto-approve

      - name: Aviso se não confirmou destroy
        if: >
          github.event.inputs.action == 'destroy' &&
          github.event.inputs.confirm_destroy != 'DESTROY'
        run: echo "Destroy não executado. Confirmação inválida."